### ISSUE TITLE
A note on using SSM Parameter Store for storing secrets

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#18]
Not an issue, but I wanted to document my decision making on this somewhere. @postfalk, this might be relevant to keep in mind as we work on developing serverless best practices. 

Originally, we were using .env files to store secrets and sensitive config values (DB connection strings, API keys, etc.). However, this got clunky and hard to maintain because often the same secrets are used by multiple individual stacks (animl-ingest, animl-api, animl-frontend), each of which have their own .env, and in some cases some of those shared values are generated dynamically by the Serverless stack build process (e.g. API Gateway entrypoints, SQS URLs).

**Option 1: Cloudfront cross-stack-references**
At first I tried using [Cloudfront Outputs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) and creating cross-stack-references to import them into other serverless stacks. Essentially, within each stack's Serverless config file, you can concat AWS vars to create some of those dynamic strings (e.g. API gateway URL, SQS URL), which can then be passed directly into that specific stack environment and/or Output to be available to other stacks:

From animl-api serverless.yml file:
```yml
  ...
  custom:
    apiUrl: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}/
    inferenceQueueUrl: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/inferenceQueue-${self:provider.stage}
    imagesUrl: ${cf:animl-ingest.imagesUrl-${opt:stage, self:provider.stage, 'dev'}}  # importing values created by other stacks
  environment: 
    ANIML_API_URL: ${self.custom.apiUrl}
    INFERENCE_QUEUE_URL: ${self.custom.inferenceQueueUrl}
    ANIML_IMAGES_URL: ${self.custom.imagesUrl}
  ...
  Outputs:
    animlApiUrl:
      Value: ${self.custom.apiUrl}
      Export:
        Name: animlApiUrl-${opt:stage, self:provider.stage, 'dev'}. # exporting values to be available to other stacks
```

From animl-ingest serverless.yml file:
```yml
  Outputs:
    imagesUrl:
      Description: Cloudfront distro domain name for image bucket
      Value: { "Fn::GetAtt": ["CloudfrontDistributionAnimldataproduction", "DomainName"] }
      Export:
        Name: imagesUrl-${opt:stage, self:provider.stage, 'dev'}
```

The advantages of this are that if those if dynamically created values change, they would be automatically pulled into the stack's env and also made available to others. However, there are a bunch of disadvantages: other stacks would still have to redeploy to get the updated URLs if they were to change, it creates a convoluted web of outputs and imports that will be hard to maintain, we'd still have a bunch of other env variables (e.g. API keys) that are not Serverless outputs that we need to manage, and the frontend doesn’t use Serverless at all so we'd still be manually keeping those values in sync.

Clearly, a centralized store for these variables seemed sensible. 

**Option 2: SSM Parameter Store**
After reading up a [bit](https://www.serverless.com/blog/aws-secrets-management) on cloud-based secrets management options, it seemed like the AWS [SSM Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html) would offer a simple, cheap, secure tool to store and retrieve secrets and shared config data, with the caveat that we'd still need to manually create and manage the keys & values in the AWS console*. Another nice advantage of this is that while we could [pull SSM values in the serverless.yml config files](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-the-ssm-parameter-store), we can also use the AWS SDK to fetch SSM values at runtime, so we wouldn't have to redeploying stacks that depend on certain SSM parameters every time they change. 

Anyhow, that's the route I've taken for now, and so far I'm pretty happy with it.

*Future improvement idea: one way to add dynamically created Serverless Output values to the Parameter Store from the serverless build process might be to use [serverless-stack-output](https://www.serverless.com/plugins/serverless-stack-output) plugin, which allows you to hook in a custom script that takes in the output as an argument. We could write an output handler script that uses the AWS-SDK’s SSM class to put and/or update those dynamically generated outputs in the parameter store.
