### ISSUE TITLE
Update container based lambda functions to include `provenance: "false"`

### ISSUE THREAD

**Issue by lessej** [tnc-ca-geo/animl-api#325]
**Scope**
This issue applies to any container based lambda function across the animl stack:

- [ ] [animl-frontend](https://github.com/tnc-ca-geo/animl-frontend)
- [ ] [animl-api](https://github.com/tnc-ca-geo/animl-api)
- [ ] [animl-ingest](https://github.com/tnc-ca-geo/animl-ingest)
- [ ] [others](https://github.com/orgs/tnc-ca-geo/repositories?q=animl)

**Context**
When deploying the animl-ingest serverless stack, we began running into the following error:

> ServerlessError2: An error occurred: IngestDeleteLambdaFunction - Resource handler returned message: "The image manifest, config or layer media type for the source image is not supported.

This was likely caused by newer versions of Docker:

> The root issue here seems to be that in newer versions of Docker, docker build [creates provenance attestations by default](https://docs.docker.com/reference/cli/docker/buildx/build/#provenance), unless disabled by the --provenance false command line option. Having the provenance attestation present causes an image index to be pushed to the registry and this is a problem with AWS Lambda.

**Fix**
The issue was fixed in animl-ingest by setting the `provenance: "false"` configuration flag in the `serverless.yml` file

```
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  profile: animl

  ecr:
    images:
      zip:
        path: ./ingest-zip/
        platform: linux/amd64
        provenance: "false"
      image:
        path: ./ingest-image/
        platform: linux/amd64
        provenance: "false"
      delete:
        path: ./ingest-delete/
        platform: linux/amd64
        provenance: "false"
```

**Task**
It's likely that other container based lambda functions in the animl stack will have the same issue during deployment.  When encountered, they should be updated to use the `provenance: "false"` flag.

**References**
- https://stackoverflow.com/questions/78482132/serverless-lambda-deploy-with-container-image-getting-the-image-manifest-or-lay
- https://www.serverless.com/framework/docs/providers/aws/guide/functions#referencing-container-image-as-a-target
- https://docs.docker.com/build/metadata/attestations/slsa-provenance/
